"""Set name fields unique

Revision ID: 53631d711f4d
Revises: 731e226c9f68
Create Date: 2024-09-09 16:45:15.976135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53631d711f4d'
down_revision: Union[str, None] = '731e226c9f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'students', ['name'])
    op.create_unique_constraint(None, 'teachers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    # ### end Alembic commands ###
