"""Update migration

Revision ID: 731e226c9f68
Revises: 7526ecbb620e
Create Date: 2024-09-09 13:37:40.053535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731e226c9f68'
down_revision: Union[str, None] = '7526ecbb620e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_teacher',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'teacher_id')
    )
    op.drop_index('ix_my_table_id', table_name='my_table')
    op.drop_index('ix_my_table_name', table_name='my_table')
    op.drop_table('my_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='my_table_pkey')
    )
    op.create_index('ix_my_table_name', 'my_table', ['name'], unique=False)
    op.create_index('ix_my_table_id', 'my_table', ['id'], unique=False)
    op.drop_table('student_teacher')
    op.drop_table('teachers')
    op.drop_table('students')
    # ### end Alembic commands ###
